### ISSUE TITLE
Support spaces in search

### ISSUE THREAD

**Issue by jwoolley** [GoodGamery/mtgcardfinder#30]
Supported for spaces in search terms would be useful in a few cases:

- searching for names with no spaces ```not name:" "```
- specifically matching spaces around words ```name:" and "``` (matches "Tooth and Nail" but not "Eight-and-a-Half-Tails")

probably the search term should be quoted for spaces to be included.

**Comment by mdiehr** [comment]
These are already supported, but you can't use the default word-boundary mode - you need "any substring", which uses a ? prefix in the search term.
`q=name:"?+or+"`
`q=not+name:"?+"`

Example: https://goodgamery.com/api/mtg/card/html?q=name:%22?+and+%22
